version: "3.9"

services:
  pg-bench-env:
    build:
      context: ..
      dockerfile: bench/Dockerfile
    container_name: pg-bench-env
    tty: true
    stdin_open: true
    volumes:
      - ..:/app
      - /app/node_modules
    working_dir: /app/bench
    environment:
      - PGHOST=db
      - PGUSER=user
      - PGPASSWORD=pass
      - PGDATABASE=data
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports: 
      - 5432:5432
    command: postgres -c password_encryption=md5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-local=md5"
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data